In [1]:
#Numpy is a scientific computing Python package, that mostly helps in n-dimensional arrays. It works on ndarrays, and provides mathematical,
#logical, sorting, and linear algebra, statistics, etc.

In [3]:
import numpy as np

In [6]:
a = np.array([1,2,5,7])

In [7]:
a

array([1, 2, 5, 7])

In [11]:
a= np.array(a,dtype=float)

In [12]:
a

array([1., 2., 5., 7.])

In [13]:
b = np.arange(1,11,2)

In [14]:
b

array([1, 3, 5, 7, 9])

In [17]:
a.reshape(2,2)

array([[1., 2.],
       [5., 7.]])

In [19]:
b.reshape(2,5)

ValueError: cannot reshape array of size 5 into shape (2,5)

In [29]:
c = np.ones((3,4))

In [30]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
d = np.random.random((3,4))

In [110]:
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
e = np.identity(4)

In [38]:
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
f = np.linspace(-10,10,11)

In [52]:
f

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.])

In [58]:
d1 = np.arange(8)
d2 = d1.reshape(2,4)
d3 = d1.reshape(2,2,2)

In [64]:
d.ndim

2

In [67]:
print(d.shape)

(3, 4)


In [69]:
d1.itemsize

8

In [70]:
f.itemsize

8

In [74]:
c.dtype

dtype('float64')

In [75]:
a2

NameError: name 'a2' is not defined

In [87]:
a1 = np.arange(22,32).reshape(2,5)

In [88]:
a1.astype('int32')

array([[22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]], dtype=int32)

In [89]:
a2 = np.arange(45,55).reshape(2,5)

In [90]:
a2

array([[45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [92]:
#Attributes: 
a.ndim
a.dtype
a.itemsize
a.size
a.shape

1

dtype('float64')

8

4

(4,)

In [93]:
a

array([1., 2., 5., 7.])

In [94]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
c *2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [96]:
c-0.5

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [97]:
c==1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [98]:
a1

array([[22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]])

In [99]:
a2

array([[45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [100]:
a1 +a2

array([[67, 69, 71, 73, 75],
       [77, 79, 81, 83, 85]])

In [101]:
a1>a2

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [102]:
d

array([[0.1871301 , 0.3300375 , 0.79246123, 0.45862069],
       [0.24165314, 0.43550575, 0.940974  , 0.06306764],
       [0.15389377, 0.50412118, 0.68655233, 0.46423665]])

In [112]:
d = np.round(d*100)

In [113]:
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [116]:
ran = np.random.random((3,3))
ran = np.round(ran*100)
ran

array([[65., 57., 75.],
       [92., 25., 75.],
       [64., 78., 13.]])

In [117]:
np.min(ran, axis=1)

array([57., 25., 13.])

In [119]:
np.tan(ran)

array([[-1.47003826,  0.48469923, -0.42070095],
       [ 1.24427006, -0.13352641, -0.42070095],
       [ 2.34786031, -0.59918   ,  0.46302113]])

In [120]:
ran2 = np.arange(11,23).reshape(3,4)

In [121]:
ran2

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [122]:
np.dot(ran,ran2)

array([[2995., 3192., 3389., 3586.],
       [2812., 3004., 3196., 3388.],
       [2121., 2276., 2431., 2586.]])

In [123]:
ran[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [124]:
ran[2,2]

np.float64(13.0)

In [125]:
ran.T

array([[65., 92., 64.],
       [57., 25., 78.],
       [75., 75., 13.]])

In [126]:
ran

array([[65., 57., 75.],
       [92., 25., 75.],
       [64., 78., 13.]])

In [127]:
ran.ravel()

array([65., 57., 75., 92., 25., 75., 64., 78., 13.])

In [129]:
a = [ i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [139]:
import numpy as np
b = np.arange(10000000,dtype='int8')
sys.getsizeof(b)

10000112

In [140]:
np.max(b)

np.int8(127)

In [143]:
b.shape

(10000000,)